about_us:
  url:   /about_us
  param: { module: site, action: aboutUs }

announcements:
  url:   /announcements
  param: { module: projectAnnouncement, action: list }

project:
  url:   /projects/:id
  param: { module: project, action: show }

projects:
  url:   /projects
  param: { module: project, action: list }

# default rules
homepage:
  url:   /
  param: { module: site, action: index }

default_symfony:
  url:   /symfony/:action/*
  param: { module: default }

default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*