generator:
  class:              sfPropelAdminGenerator
  param:
    model_class:      Website
    theme:            default

    fields:
      summary:        { type: textarea_tag, params: size=100x5 }
      description:    { params: size=100x20 }

    list:
      display:        [=name, url, summary]

    edit:
      display:        [name, slogan, summary, description, url]