generator:
  class:              sfPropelAdminGenerator
  param:
    model_class:      User
    theme:            default

    list:
      display:        [_photo, =username, email, first_name, last_name, created_at]

    edit:
      fields:
        photo:
          type:       admin_input_file_tag
          upload_dir: pictures/users
          params:     include_link=pictures/users include_remove=true
        created_at:   { type: plain }
      display:        [username, email, first_name, last_name, photo, created_at]