generator:
  class:              sfPropelAdminGenerator
  param:
    model_class:      Project
    theme:            default

    fields:
      summary:        { type: textarea_tag, params: size=100x5 }
      description:    { params: size=100x20 }

    list:
      display:        [=name, license]

    edit:
      fields:
        project_developer: { type: admin_double_list, params: through_class=ProjectDeveloper }
      display:        [name, summary, description, license_id, wiki, issue_tracker, forums, download, project_developer]