generator:
  class:              sfPropelAdminGenerator
  param:
    model_class:      Developer
    theme:            default

    list:
      display:        [=user, organization_name, organization_url]

    edit:
      display:        [user_id, organization_name, organization_url]